import type { DeviceSettings } from '../types';

export interface PlantProfile {
    id: string;
    name: string;
    description: string;
    settings: Partial<DeviceSettings>;
}

export const PLANT_PROFILES: PlantProfile[] = [
    {
        id: 'cactus',
        name: 'Cactus / Succulent',
        description: 'Dry loving plants. Infrequent watering, low moisture.',
        settings: {
            soil_min: 10,
            soil_max: 30,
            temp_min: 15,
            temp_max: 35,
            hum_min: 10,
            hum_max: 40,
            light_min: 2000,
            light_max: 50000,
            watering_duration_sec: 5,
            measurement_interval_sec: 3600, // 1 hour
        },
    },
    {
        id: 'fern',
        name: 'Fern',
        description: 'Moisture loving. Needs high humidity and shade.',
        settings: {
            soil_min: 60,
            soil_max: 80,
            temp_min: 18,
            temp_max: 24,
            hum_min: 60,
            hum_max: 90,
            light_min: 500,
            light_max: 2000,
            watering_duration_sec: 15,
            measurement_interval_sec: 1800, // 30 min
        },
    },
    {
        id: 'basil',
        name: 'Basil',
        description: 'Warm and sunny. Consistent moisture.',
        settings: {
            soil_min: 40,
            soil_max: 70,
            temp_min: 20,
            temp_max: 30,
            hum_min: 40,
            hum_max: 70,
            light_min: 4000,
            light_max: 20000,
            watering_duration_sec: 10,
            measurement_interval_sec: 1800,
        },
    },
    {
        id: 'tomato',
        name: 'Tomato',
        description: 'Thirsty and sunny. High light and water.',
        settings: {
            soil_min: 50,
            soil_max: 80,
            temp_min: 18,
            temp_max: 30,
            hum_min: 40,
            hum_max: 80,
            light_min: 5000,
            light_max: 30000,
            watering_duration_sec: 20,
            measurement_interval_sec: 1800,
        },
    },
    {
        id: 'orchid',
        name: 'Orchid',
        description: 'Specialized care. High humidity, diffused light.',
        settings: {
            soil_min: 30,
            soil_max: 60,
            temp_min: 18,
            temp_max: 28,
            hum_min: 50,
            hum_max: 80,
            light_min: 1000,
            light_max: 5000,
            watering_duration_sec: 8,
            measurement_interval_sec: 3600,
        },
    },
    {
        id: 'snake_plant',
        name: 'Snake Plant',
        description: 'Very hardy. Low light and water tolerance.',
        settings: {
            soil_min: 15,
            soil_max: 40,
            temp_min: 15,
            temp_max: 30,
            hum_min: 30,
            hum_max: 60,
            light_min: 500,
            light_max: 10000,
            watering_duration_sec: 8,
            measurement_interval_sec: 3600,
        },
    },
    {
        id: 'monstera',
        name: 'Monstera',
        description: 'Tropical climber. Moderate water and indirect light.',
        settings: {
            soil_min: 40,
            soil_max: 70,
            temp_min: 18,
            temp_max: 30,
            hum_min: 50,
            hum_max: 80,
            light_min: 1000,
            light_max: 5000,
            watering_duration_sec: 12,
            measurement_interval_sec: 1800,
        },
    },
    {
        id: 'peace_lily',
        name: 'Peace Lily',
        description: 'Shade lover. Droops when thirsty.',
        settings: {
            soil_min: 50,
            soil_max: 80,
            temp_min: 18,
            temp_max: 26,
            hum_min: 50,
            hum_max: 80,
            light_min: 200,
            light_max: 1500,
            watering_duration_sec: 10,
            measurement_interval_sec: 1800,
        },
    },
    {
        id: 'pothos',
        name: 'Pothos',
        description: 'Vining plant. Flexible light and water needs.',
        settings: {
            soil_min: 30,
            soil_max: 70,
            temp_min: 15,
            temp_max: 30,
            hum_min: 30,
            hum_max: 70,
            light_min: 500,
            light_max: 3000,
            watering_duration_sec: 10,
            measurement_interval_sec: 3600,
        },
    },
    {
        id: 'aloe_vera',
        name: 'Aloe Vera',
        description: 'Succulent medicinal plant. Bright light, dry soil.',
        settings: {
            soil_min: 20,
            soil_max: 40,
            temp_min: 15,
            temp_max: 30,
            hum_min: 30,
            hum_max: 50,
            light_min: 3000,
            light_max: 20000,
            watering_duration_sec: 8,
            measurement_interval_sec: 3600,
        },
    },
];
